### ISSUE TITLE
Help with Gatsby Image

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#147]
@pcast01,
Can you help me bring in the images here with Gatsby images?

https://github.com/sacodersunited/cbet/blob/83925425f5ccf8cd8fe8564815ad660c3fbe22dc/src/components/testimonials.js#L52

**Comment by pcast01** [comment]
@fpigeonjr I have fixed the issue with them. Take a look, there is an issue with the width of the images.
