### ISSUE TITLE
Add Azure Auth to cbet for CRUD of content.

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#169]
**TODO:**

- [x] add cbet auth
- [x] hide keys in ENV

**Comment by pcast01** [comment]
Added Cbet Authentication in feature/add-cbet-auth

**Comment by pcast01** [comment]
Next up is to hide the keys away in an ENV file.

**Comment by fpigeonjr** [comment]
@pcast01 I am going to move this to closed on the project board.
