### ISSUE TITLE
dynamically generate blog pages for blog posts

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#170]
**url**

`/posts/blog-title-slug`

**template**

- [x] create template
- [x] create post with gatsby config

**Comment by fpigeonjr** [comment]
@pcast01 Can you help me with creation of post pages in the `gatsby-node.js`?

**Comment by pcast01** [comment]
I can do it.

**Comment by fpigeonjr** [comment]
> 
> 
> I can do it.

Thanks @pcast01! That would be a big help and I work on the templates.

**Comment by pcast01** [comment]
Done.
