### ISSUE TITLE
Refactor Navigation

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#176]
Make room for the countdown timer by refactoring navigation with nested items.

Can't remember what we can nest so need to check my notes.

**Comment by fpigeonjr** [comment]
@pcast01 do you remember what the navbar changes were?

**Comment by pcast01** [comment]
Not sure. Do you mean in the meeting?

**Comment by fpigeonjr** [comment]
> Not sure. Do you mean in the meeting?

Yeah, we'll prob have to check with the client again.
