### ISSUE TITLE
Refactor frontend to pull data from azure

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#179]
Currently frontend is pulling from yaml files (except for blogs).
Need to refactor to pull from Azure database.

TODO:

- [x] add data to match staging
- [x] refactor to pull data from Azure

**Comment by fpigeonjr** [comment]
@pcast01 Can you please some logo images, start dates, and links to the database?

![image](https://user-images.githubusercontent.com/4629398/80312552-6280ff80-87ab-11ea-8cd8-51f3f70a409f.png)

**Comment by fpigeonjr** [comment]
also do we have a time utility to parse the dates coming from Azure?

![image](https://user-images.githubusercontent.com/4629398/80315350-8dc01a80-87bc-11ea-8e8d-0ca53a4a45a5.png)

**Comment by pcast01** [comment]
No we don't. You will have to create one.

**Comment by fpigeonjr** [comment]
> No we don't. You will have to create one.

Gotcha, what format are trying to convert from?

**Comment by pcast01** [comment]
SQL Server date.
