### ISSUE TITLE
Get correct image size for branding for Background image and Banner logo

### ISSUE THREAD

**Issue by pcast01** [sacodersunited/cbet#189]
![azure_auth_branding](https://user-images.githubusercontent.com/1172644/80768806-03a3e900-8b11-11ea-8d59-f661d239f916.png)

**Comment by fpigeonjr** [comment]
Got it, I'll take a look this weekend @pcast01 . We can prob use a lot of their existing branding for this.

**Comment by pcast01** [comment]
Yeah agreed 🤝.

**Comment by fpigeonjr** [comment]
@pcast01 Uploaded assets here:
[sacoders gogle drive](https://drive.google.com/drive/u/0/folders/1jhMUCuAZ5Tdl6C_ygMjwF7JlprfDkIzm)

![image](https://user-images.githubusercontent.com/4629398/80927058-e5342c80-8d60-11ea-8677-17a323d83179.png)

also signin bg color should be `#191b28`

**Comment by pcast01** [comment]
Here is what it looks like.
![image](https://user-images.githubusercontent.com/1172644/80967322-c45ced00-8ddb-11ea-9526-35737425519f.png)

**Comment by pcast01** [comment]
Frank, I re-opened this issue because the image for the banner has to be 10kb or less. I compressed the banner logo to 5.44 kb but I think it might look bad. Can you take a look at changing your asset to be 10kb or less?

**Comment by fpigeonjr** [comment]
@pcast01 that login page looks great! I'll take a look at the banner. So its too big right now and needs to be compressed more?

**Comment by pcast01** [comment]
Yes.

ᐧ

**Comment by fpigeonjr** [comment]
uploaded compressed image to sacoders gdrive.
got it using `jpegoptim`
![image](https://user-images.githubusercontent.com/4629398/80977973-12c5b800-8deb-11ea-93d4-1e70938fd9df.png)
