### ISSUE TITLE
Add Gatsby Incremental build to project

### ISSUE THREAD

**Issue by pcast01** [sacodersunited/cbet#194]
Steps to add incremental builds

[Instructions](https://www.netlify.com/blog/2020/04/23/enable-gatsby-incremental-builds-on-netlify/?utm_campaign=Gatsby+Builds+Promo+Email&utm_content=Gatsby+Builds+Promo+Email&utm_medium=email_action&utm_source=customer.io)

**Comment by fpigeonjr** [comment]
@pcast01 is this still an open issue?

**Comment by pcast01** [comment]
@fpigeonjr Yes, until we deploy the latest cbet changes.

**Comment by fpigeonjr** [comment]
check production deploys on netlify to confirm if they are there.

**Comment by fpigeonjr** [comment]
I think we can close this. It is on by default in Gatsby 3.
