### ISSUE TITLE
Create image with a default upload image and also a similar one with a green signifying that it is hovered over for dropzone.

### ISSUE THREAD

**Issue by pcast01** [sacodersunited/cbet#198]
Frank can you make the image for the dropzone to be like this but then also a version that is Green in the middle to signify that you are hovering over it with a file?

![image](https://user-images.githubusercontent.com/1172644/81361962-5b0fff00-90a5-11ea-9326-301a4ae070e6.png)

**Comment by fpigeonjr** [comment]
Uploaded to the **sacoders gdrive**.

`sacoders/cbet/assets`

![image](https://user-images.githubusercontent.com/4629398/81505473-0216b580-92b5-11ea-84c6-7f05b25df1a6.png)

**Comment by pcast01** [comment]
Can you make one more and change it to say "uploading..."?

**Comment by fpigeonjr** [comment]
now we have 4 states for dropzone

![image](https://user-images.githubusercontent.com/4629398/81598286-a91a5080-938c-11ea-911c-6c05261ea25a.png)
