### ISSUE TITLE
Create Form Fixes

### ISSUE THREAD

**Issue by pcast01** [sacodersunited/cbet#206]
Event
- [x] remove Author
- [x] remove Event Content
- [x] remove Thumbnail
- [x] add link 
- [x] remove html editor

Job 
- [x] add link
- [x] remove html editor 
- [x] remove thumbnails and use with partner selection
- [x] Add job description

Blog
- [x] add header image upload
- [x] requires 1440 x 300 

html editor toolbar
- [ ] Add headers

Other
- [x] Add all partner images to azure storage

**Comment by fpigeonjr** [comment]
@pcast01 can you add the link in the footer to `/admin` too?

**Comment by pcast01** [comment]
Completed all but toolbar add headers.
