### ISSUE TITLE
update course dates

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#211]
Course dates seem to be outdated.
![image](https://user-images.githubusercontent.com/4629398/82125143-98415480-9769-11ea-8256-5cd1b5b18825.png)

Based on the calendar pdf, the next semester starts in June.
![image](https://user-images.githubusercontent.com/4629398/82125169-d179c480-9769-11ea-936c-8fa948c4227e.png)

**Comment by pcast01** [comment]
Done.
