### ISSUE TITLE
Create "authenticating..." in cbet style in Admin Layout

### ISSUE THREAD

**Issue by pcast01** [sacodersunited/cbet#216]
Frank, can you create a better look for "authenticating..." src\components\admin\layout.js starting at line 174?

**Comment by fpigeonjr** [comment]
sure thing, but how would I get to app in this state?

**Comment by pcast01** [comment]
In only happens when logging in. So you have to logout. All you have to do is add a button using the unused logout function.

**Comment by fpigeonjr** [comment]
:smile: thanks, I'll take a look this weekend.
