### ISSUE TITLE
cannot update Blog Header image

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#221]
Steps to reproduce

1. Go to admin->blog
1. Edit a Blog
1. Upload a different header image
1. 😭 same image is still there

**Comment by fpigeonjr** [comment]
hmmm, also notice I can't update other items without re-uploading another **Header Image**

**Comment by pcast01** [comment]
> hmmm, also notice I can't update other items without re-uploading another **Header Image**

🤔 I will take a look at this how I coded this.

**Comment by pcast01** [comment]
I found out the issue. In my stored procedure I update I didn't update the Thumbnail URL. I updated the code to include that on an Edit.
