### ISSUE TITLE
cannot change Blog state to active

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#222]
Steps to reproduce

1. Create a new blog
1. Defaults to disabled
1. Change status to **Active**
1. 😭 still show disabled on card but not in Edit

**Comment by pcast01** [comment]
I will take a look at this now.

**Comment by pcast01** [comment]
I fixed this now. The Status wasn't being shown correctly when selecting a Job, Event or Blog. But now it shows the right value and saves correctly.
