### ISSUE TITLE
Editing Issues

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#225]
Editing some categories I am seeing weird results on `dev` branch.

**Steps To Reproduce**

1. Edit **Event**
1. Change Event Location and Title
1. Save
1. 😢State does not change

Another test of  **Jobs**
1. Edit **Job**
1. Change Description
1. Change Author
1. Save
1. 😭 State does not change

**Comment by fpigeonjr** [comment]
🤔hmmmm, also unable to change content on blog post...

**Comment by pcast01** [comment]
Found out I accidentally put the Status field as a string instead of a boolean.
