### ISSUE TITLE
New Phone Number - 844-879-9043

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#239]
Good evening and happy Friday, everyone.
We needed to make a few necessary changes to our phone plan.  As a result, our toll free number has changed. 

Please modify your signature e-mail signature blocks, social media, and any other documents (syllabi, etc.) that you control to reflect the new toll free phone number: 

 Toll Free:  844-879-9043

 All other numbers remain the same – thank you so much.   Have a great weekend everyone and thanks for all of the hard work and going the extra mile on so many different projects – amazing team.   

Respectfully,
Richard L. “Monty” Gonzales

**Comment by pcast01** [comment]
Updated in footer and hr page.
