### ISSUE TITLE
New Strategic Partner

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#253]
Hey guys,
On your laundry list of items please add one more.

WE have a new strategic partner, an HTM Associate from Hawaii. 

Here is the link to their webpage:  https://www.hihtm.com/

They do not have a nice crisp/clean logo to grab so you may need to tinker with this one just a bit to get a good clean image.  Please let me know if you need something else on this one. 

Thank you.
Respectfully,
Richard L. “Monty” Gonzales
Director, College of Biomedical Equipment Technology
11550 IH 10 West, Suite 190 | San Antonio | Texas  78230
O 210.233.1102  |  TF 866.866.9027  |  M 580.583.6817 | F 210.855.2245

**Comment by pcast01** [comment]
@fpigeonjr Can you get an image for this new partner? I can add it to the site and to the backend. I just can't find an easy way to get their logo in an image for use to use.

**Comment by fpigeonjr** [comment]
working on this now, I'll get something from this.
<img width="983" alt="Screen Shot 2020-07-15 at 9 29 39 PM" src="https://user-images.githubusercontent.com/4629398/87619680-63f30180-c6e2-11ea-8694-a14f355a4147.png">

**Comment by fpigeonjr** [comment]
ok @pcast01, try this. I made it the same dimensions as the MedWrench logo which is 215x65 px.
![hihtm-logo](https://user-images.githubusercontent.com/4629398/87620276-bed92880-c6e3-11ea-9027-236a8742663f.png)

**Comment by pcast01** [comment]
Added this to master now.
