### ISSUE TITLE
Catalog to Flipbook

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#268]
Change Catalog on our site to the Flipbook embed below.

Flipbook embed code:
<iframe src="https://cdn.flipsnack.com/widget/v2/widget.html?hash=fxu8o9jug" width="100%" height="480" seamless="seamless" scrolling="no" frameBorder="0" allowFullScreen></iframe>

**Comment by fpigeonjr** [comment]
I think in my last implementation of this I created a page called `Catalog` or something and just placed the embed code there so it seems like it is part of the site.

And don't forget to add responsive embed css.

**Comment by pcast01** [comment]
Got it implemented on a page called course-catalog.
