### ISSUE TITLE
Update Calendar

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#270]
-New Calendar with updated Phone number (attached)
[CBET _Academic_Calendar_2020-2021_08112020.pdf](https://github.com/sacodersunited/cbet/files/5059642/CBET._Academic_Calendar_2020-2021_08112020.pdf)

**Comment by pcast01** [comment]
Added pdf to site and changed it to reference in the Footer.js file and Schedule.js file

**Comment by fpigeonjr** [comment]
Can we close this issue @pcast01?
