### ISSUE TITLE
Remove Quickschool Application on Admission page

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#274]
-The admissions page, we've decided to kill off the Quickschools Application web form. The inquiry form on the top bar is great, but the second enrollment web form is redundant since we require students to complete the adobe sign PDF in order to apply. We'd like to just place a button to download the Adobe sign application PDF, with instructions to complete and email to admissiondept@cbet.edu. I owe you the verbiage and the PDF, which we are finalizing still, but I wanted to put this on your radar as we will want to move quickly when we have it.

**Comment by pcast01** [comment]
Removed nav header link and admissions page for now.

**Comment by fpigeonjr** [comment]
The client will need to provide the pdf that will go on the Admissions page.

**Comment by pcast01** [comment]
Added back the admissions page.
