### ISSUE TITLE
Weekly Batch Updates

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#285]
Frank, Paul,

Here are the batch changes we need to make:

- [X] Under accreditations we need to add BPPE (logo attached). Linked out to  https://www.bppe.ca.gov/
- [x] The Academic calendar had a typo in Fall 2 dates, so it needs to be updated (attached).
- [x] When the Enrollment Term time limit ends, instead of it saying "Time is up..." Can we reword that to read "Contact us to register today. New Enrollment period begins next week." (I don't want students to be shut down by the messaging that's designed to create urgency).
- [x] cbet.edu/bmet-certificate - Course content bullets need to change to: 
   - Medical Terminology & Anatomy
   - Electronics I
   - Networking Fundamentals I
   - Biomedical Equipment Technology I
   - Capstone
- [x] On the Student endorsements there seems to be two views, condensed and expanded, but neither of them display the testimonials in a uniform way. (See screenshots a & b). Ideally I'd like to have a different view that makes all of these more uniform, and clean.

Let me know if you have any questions, and please just shoot me an email when you have these completed. Thank you for your work on this! 

Matthew Bassuk
Director of Learning Technologies
College of Biomedical Equipment Technology
210.245.7896 x1007

![a](https://user-images.githubusercontent.com/4629398/94318459-40ec9580-ff4e-11ea-98fc-feb82a336022.png)
![b](https://user-images.githubusercontent.com/4629398/94318466-43e78600-ff4e-11ea-9b6e-7b460848154e.png)
![bppe_logo](https://user-images.githubusercontent.com/4629398/94318469-4518b300-ff4e-11ea-9890-2fbc0cb988c7.png)
[CBET_2020-2021_Academic_Calendar_v92420.pdf](https://github.com/sacodersunited/cbet/files/5285505/CBET_2020-2021_Academic_Calendar_v92420.pdf)

**Comment by fpigeonjr** [comment]
@pcast01 Started fixes on the `hotfix/issue285` branch.

**Comment by fpigeonjr** [comment]
taking a breaks for now. Also any suggestions on normalizing the height of the cards @pcast01 ?

**Comment by pcast01** [comment]
> taking a break for now. Also any suggestions on normalizing the height of the cards @pcast01 ?

You are talking about his last item on the testimonials right?

**Comment by fpigeonjr** [comment]
> > taking a break for now. Also any suggestions on normalizing the height of the cards @pcast01 ?
> 
> 
> 
> You are talking about his last item on the testimonials right?

yes the last checkbox item

**Comment by pcast01** [comment]
I'm gonna take a look at it now.

**Comment by fpigeonjr** [comment]
ok @pcast01 I pushed up a possible solution to fix the testimonial cards. Will PR now.
