### ISSUE TITLE
CBET Weekly issues

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#290]
1. We have a new Academic Calendar that we'd like to add to the website. 

2. Also, Mortega@cbet.edu Needs access to the admin portal. I didn't see a way to create an admin.

Thanks!

Matthew Bassuk
Director of Learning Technologies
College of Biomedical Equipment Technology
210.245.7896 x1007

**Comment by fpigeonjr** [comment]
@pcast01 submitted PR to address item 1. 
Can you please add the user in item 2?

**Comment by pcast01** [comment]
I added the user.
