### ISSUE TITLE
Weekly Updates from Client

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#306]
- [x] About page: 
  - Values first item: remove "...a World-Class Education on Demand" replace with "...the Highest Quality Education". 
  - Values first item: we need to change "...focused on state of the art equipment,... " to "...focused on both general and advanced biomedical equipment,..." 

- [x] Please change the Ultrasound video on the BMET Certificate page to one of these instead: 
https://1drv.ms/v/s!ApbM2Y5o92Q1hMpgEMgKsRZroYVHMw?e=GEMOOc
https://1drv.ms/v/s!ApbM2Y5o92Q1hMph6WYnQKYOfo8ADQ?e=mBmNg9
https://1drv.ms/v/s!ApbM2Y5o92Q1hMpipiDU6XdmXnCHDA?e=zJsGXg
https://1drv.ms/v/s!ApbM2Y5o92Q1hMpuXv8vNVxnpS_0LA?e=YuZYEq

- [x] Also, if possible I'd like to get access to our Google Analytics. I'm trying to get a better understanding of where our traffic is coming from. Thanks!

Have a great weekend.

Matthew Bassuk
Director of Learning Technologies
College of Biomedical Equipment Technology
210.245.7896 x1007

**Comment by fpigeonjr** [comment]
@pcast01 Can you work the Google Analytics add?

**Comment by pcast01** [comment]
Yes. I will work on it.

**Comment by pcast01** [comment]
Frank, I have added Matt to GA.

![image](https://user-images.githubusercontent.com/1172644/102383904-b4240780-3f91-11eb-87f0-0fdb59c8cc2b.png)

**Comment by pcast01** [comment]
@fpigeonjr Can you please PR to Development and Staging Branches?

**Comment by fpigeonjr** [comment]
> @fpigeonjr Can you please PR to Development and Staging Branches?

No problem @pcast01 but we may need to look at our branching strategy again.
