### ISSUE TITLE
Add seal to footer

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#312]
Guys would you mind adding this seal somewhere on the footer of the site. Thanks.

 <div class="AuthorizeNetSeal"> <script type="text/javascript" language="javascript">var ANS_customer_id="99ab4f3f-9725-46ec-8c74-e9e512ba8d79";</script> <script type="text/javascript" language="javascript" src="//verify.authorize.net:443/anetseal/seal.js" ></script> </div>  

Matthew Bassuk
Director of Learning Technologies
College of Biomedical Equipment Technology
210.245.7896 x1007

**Comment by fpigeonjr** [comment]
@pcast01 Not really sure what this is supposed to do...any ideas?

**Comment by pcast01** [comment]
I think we should just add it like we would GA.

**Comment by pcast01** [comment]
@fpigeonjr Did you try to add this using Helmet. https://stackoverflow.com/questions/61877792/add-script-tag-in-gatsby

**Comment by pcast01** [comment]
@fpigeonjr Here is the code that the seal.js has in it.
`var ANSVerificationURL="https://verify.authorize.net/anetseal/";var AuthorizeNetSeal={verification_parameters:"",id_parameter_name:"pid",url_parameter_name:"rurl",seal_image_file:(ANSVerificationURL+"images/secure90x72.gif"),seal_width:"90",seal_height:"72",seal_alt_text:"Authorize.Net Merchant - Click to Verify",display_url:"http://www.authorize.net/",text_color:"black",text_size:"9px",line_spacing:"10px",new_window_height:"430",new_window_width:"600",current_url:"",display_location:true,no_click:false,debug:false};document.writeln('<style type="text/css">');document.writeln('div.AuthorizeNetSeal{text-align:center;margin:0;padding:0;width:'+AuthorizeNetSeal.seal_width+'px;font:normal '+AuthorizeNetSeal.text_size+' arial,helvetica,san-serif;line-height:'+AuthorizeNetSeal.line_spacing+';}');document.writeln('div.AuthorizeNetSeal a{text-decoration:none;color:'+AuthorizeNetSeal.text_color+';}');document.writeln('div.AuthorizeNetSeal a:visited{color:'+AuthorizeNetSeal.text_color+';}');document.writeln('div.AuthorizeNetSeal a:active{color:'+AuthorizeNetSeal.text_color+';}');document.writeln('div.AuthorizeNetSeal a:hover{text-decoration:underline;color:'+AuthorizeNetSeal.text_color+';}');document.writeln('div.AuthorizeNetSeal a img{border:0px;margin:0px;text-decoration:none;}');document.writeln('</style>');if(window.ANS_customer_id)
{AuthorizeNetSeal.verification_parameters='?'+AuthorizeNetSeal.id_parameter_name+'='+encodeURI(ANS_customer_id);if(window.location.href)
{AuthorizeNetSeal.current_url=window.location.protocol+'//'+window.location.hostname;}
else if(document.URL)
{if(document.URL.toLocaleLowerCase().startsWith('https')){AuthorizeNetSeal.current_url='https://'+document.domain;}else if(document.URL.toLocaleLowerCase().startsWith('http')){AuthorizeNetSeal.current_url='http://'+document.domain;}else{AuthorizeNetSeal.current_url=document.domain;}}
if(AuthorizeNetSeal.current_url)
{AuthorizeNetSeal.verification_parameters+='&'+AuthorizeNetSeal.url_parameter_name+'='+encodeURI(AuthorizeNetSeal.current_url);}
if(!AuthorizeNetSeal.no_click)
{document.write('<a ');document.write('href="'+ANSVerificationURL+AuthorizeNetSeal.verification_parameters+'" ');if(!AuthorizeNetSeal.debug)
{document.write('onMouseOver="window.status=\''+AuthorizeNetSeal.display_url+'\'; return true;" ');document.write('onMouseOut="window.status=\'\'; return true;" ');document.write('onClick="window.open(\''+ANSVerificationURL+AuthorizeNetSeal.verification_parameters+'\',\'AuthorizeNetVerification\',\'');document.write('width='+AuthorizeNetSeal.new_window_width);document.write(',height='+AuthorizeNetSeal.new_window_height);document.write(',dependent=yes,resizable=yes,scrollbars=yes');document.write(',menubar=no,toolbar=no,status=no,directories=no');if(AuthorizeNetSeal.display_location)
{document.write(',location=yes');}
document.write('\'); return false;" ');}
document.write('rel="noopener noreferrer" target="_blank"');document.writeln('>');}
document.writeln('<img src="'+AuthorizeNetSeal.seal_image_file+'" width="'+AuthorizeNetSeal.seal_width+'" height="'+AuthorizeNetSeal.seal_height+'" border="0" alt="'+AuthorizeNetSeal.seal_alt_text+'">');if(!AuthorizeNetSeal.no_click)
{document.writeln('</a>');}}`

**Comment by fpigeonjr** [comment]
I'll try that today @pcast01 and see if I can get it.

**Comment by fpigeonjr** [comment]
getting closer but client is blocking seal.js
<img width="656" alt="Screen Shot 2021-01-25 at 1 06 25 PM" src="https://user-images.githubusercontent.com/4629398/105753372-3814cc00-5f0e-11eb-9dfe-6b3749d61db5.png">

**Comment by fpigeonjr** [comment]
@pcast01 Can you pull down branch https://github.com/sacodersunited/cbet/tree/issue312 and see if works on your system? I am wondering if its my network or environment?

**Comment by fpigeonjr** [comment]
project is sunsetting
