### ISSUE TITLE
Add new Partner

### ISSUE THREAD

**Issue by pcast01** [sacodersunited/cbet#315]
Good morning, gentlemen.

We have a new industry partner that would like us to add their company logo to our website.  We will also be providing a link to their HR page on our Career Page – so please build them in to that system as well so that their logo will populate along with any job postings. 

Thanks and have a great Saturday and Superbowl weekend.

The McConnell Group: www.themccgroup.com

**Comment by pcast01** [comment]
![TMGlogo-trans](https://user-images.githubusercontent.com/1172644/105612945-fc022f80-5d84-11eb-9367-bd294ecd6928.png)

**Comment by fpigeonjr** [comment]
@pcast01 I can work on adding to the footer area if you want to add to the Career page backend.

**Comment by pcast01** [comment]
Sure.

**Comment by pcast01** [comment]
Completed PR to master and completed the back end addition of the partner. Logo is uploaded to CBET Azure Storage: [logo](https://cbet.blob.core.windows.net/cbetblobs/tmg.png)
