### ISSUE TITLE
New Class Dates

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#319]
Good Afternoon, Gents!
 
                I hope all is well..
 
It is time to update the term dates.  Thanks. 
 
Spring 2    Start-10 May 2021    End--20 June 2021    Enrollment Deadline-3 May 2021
 
 
Respectfully,
Scott W. McKnight
Director of Education
College of Biomedical Equipment Technology
844.879.9043 Toll-Free
210.233.1102 Office
337.353.1566 Cell
www.cbet.edu

**Comment by pcast01** [comment]
Done.
