### ISSUE TITLE
Website Changes

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#320]
We have a couple high priority website updates.

Thanks,
Matt

**Certificate Page:**
Change the sentence: "Training includes basic electronics, schematics, pneumatics, hydraulics, customer service skills, environmental of care, EOC training, data management systems, and general biomedical equipment troubleshooting." to> "Students will apply skills acquired throughout their coursework in basic electronics, schematics, pneumatics, hydraulics, customer service, environment of care (EOC), and troubleshooting."

We need to update the Price and duration of the Certificate Program: 

Program Cost
$9,298 ($9198 Tuition, $100 Application Fee, Books and Supplies are Included in Tuition)

Program Length
24 Weeks Full Time / 48 Weeks Part Time
405 Clock Hours / 24.0 Semester Credits

**About page:** 
-Values first item: remove "...a World-Class Education on Demand" replace with "...Exceptional Education"

Matthew Bassuk

Director of Learning Technologies

College of Biomedical Equipment Technology

210.245.7896 x1007

**Comment by pcast01** [comment]
Completed.
