### ISSUE TITLE
Website update

### ISSUE THREAD

**Issue by pcast01** [sacodersunited/cbet#323]
One more update. Can you please change the "31 Week Certificate Course" to "24 / 48 Week Certificate Course."

Thanks!

Matthew Bassuk
![2021-04-01_13-40-08](https://user-images.githubusercontent.com/1172644/113367704-605fe300-9322-11eb-8759-618b96146806.png)

**Comment by fpigeonjr** [comment]
@pcast01 I just PR'ed this fix.

**Comment by pcast01** [comment]
@fpigeonjr it is merged.
