### ISSUE TITLE
Website Changes 4/27/2021

### ISSUE THREAD

**Issue by pcast01** [sacodersunited/cbet#327]
Change 1:  Bill’s title: Change to “Chairman and CEO, HTM Global” and also, please add the following credentials beneath his name and after his MBA, “CABT, CHOP-B; CHTM”

Change 2:  Monty’s title: Change to “President” and adjust my academic credentials from “MA” to “Ed.D.”

Change 3:  Add Matt Bassuk as part of our governing board – you will need to get Matt’s preferred professional photo for this action – not sure which one he will want to use.  His title within the organization is “Director of Learning Technologies” and his academic credentials are “MBA, MAGL”. 

UPDATE: On Bill's title don't include the CABT credential. Just CHOP-B and CHTM. Also no photo for Matt just yet.

**Comment by fpigeonjr** [comment]
possible issues...no image for Matt.
Does he have a cbet email?
Is he on LinkedIn?
