### ISSUE TITLE
consider updating to Gatsby 3

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#332]
screenshot of `npm outdated`

<img width="567" alt="Screen Shot 2021-06-11 at 9 37 46 PM" src="https://user-images.githubusercontent.com/4629398/121762711-59610800-cafd-11eb-87a2-2186208a6148.png">

**Comment by pcast01** [comment]
yeah looks like this is a good candidate for upgrading. This has a lot more images and also we should prune this down a bit as well.

**Comment by fpigeonjr** [comment]
project is sunsetting
