### ISSUE TITLE
broken image on blog post

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#333]
https://cbet.edu/posts/externship-providers-are-critical-to-the-htm-workf

<img width="1362" alt="Screen Shot 2021-06-11 at 11 10 52 PM" src="https://user-images.githubusercontent.com/4629398/121764535-486ac380-cb0a-11eb-9e8b-415d0e32d75c.png">

**Comment by fpigeonjr** [comment]
and career trends blog post

**Comment by fpigeonjr** [comment]
placeholder image should be this:
https://i.picsum.photos/id/1067/1440/300.jpg?hmac=yWv-66QaJtQCSSTcLJgXz1KElMEIS2U7NSchdGFc_t8

**Comment by pcast01** [comment]
So we should probably fix this soon. Also Master needs to be merged with staging at some point. I also see we need to delete all the other branches. Sound good on that? I can delete them.

**Comment by fpigeonjr** [comment]
yes I agree @pcast01. Let's delete all the branches we aren't using. I wonder if we even need a `staging` branch just keep `master`?

**Comment by pcast01** [comment]
Yeah let's delete staging too.

**Comment by fpigeonjr** [comment]
let's track this on #294
