### ISSUE TITLE
6.23.Client updates

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#338]
- [x] 1. We need to update our Accreditation Statement to "The College of Biomedical Equipment Technology is accredited by the Accrediting Council for Continuing Education & Training (ACCET), an accrediting agency continuously recognized by the U.S. Department of Education as a reliable authority on educational quality since 1978." 
- [x] 2. We need to change our inquiry and application web forms. We are moving away from Quickschools, and migrating to Campus Cafe. For Inquiry we can embed the form similar to the way we have it now. For the application, there are actually 2 links (Cert App and AAS App), we can just create buttons to link out to them I suppose. 
  - Here's the link for the inquiry form (We need to embed it where we have our current inquiry form): https://bio-web.scansoftware.com/cafeweb/tapestry?page=Inquiry
  - Here's the AAS Application link: https://bio-web.scansoftware.com/cafeweb/tapestry?page=AAS%20Application
  - Here's the link for the Cert Application: https://bio-web.scansoftware.com/cafeweb/tapestry?page=CERT%20Application
- [x] 3. We need to remove our IT / Networking Programs, since we are not offering them now or for the foreseeable future. We can remove the "Specialty Programs" tile as well. 

We need to be strategic about when we cutover the **Inquiry and Application forms**, so please let me know when we can get the cutover scheduled so we can coordinate a plan with the Admissions team.

**Comment by fpigeonjr** [comment]
@pcast01 Will need some help with item 3. The Specialty Program still shows on the `/schedule` page. Also need to update the class schedule.

**Comment by fpigeonjr** [comment]
Functionally this works. However, I think we have a few opportunities from a styling perspective. I'm not sure what we can do with the Campus Cafe styling. I can ask what ability there is to style these, but ideally we would be able to consolidate some of the spacing of the web forms to limit scrolling. At the very least, we need to remove the double scrollbar issue to avoid a clunky user experience. 

The other item I think we should address, is the way it's set up now. The user clicks on the apply now button on either the Certificate Page or the AAS page, those buttons take them to the specific application for those programs. Ideally the user would confirm which program they wish to apply for after clicking Apply Now from either page. (Just so they don't end up filling out the wrong application as they have different deposit amounts). Can we add a dropdown, or another way of having the user select which program they are applying for? We also have an apply Now button that goes nowhere on the homepage carousel. 

If you want to jump on a call to discuss, let me know. Thanks!
 
Matthew Bassuk
Director of Learning Technologies
College of Biomedical Equipment Technology
210.245.7896 x1007

**Comment by fpigeonjr** [comment]
MVP from above could be?

- [ ] remove the double scrollbar from iFrame
- [ ] add a dropdown, or another way of having the user select which program they are applying for?
- [ ]  apply Now button that goes nowhere on the homepage carousel

**Comment by fpigeonjr** [comment]
thanks @pcast01 for taking care of these.

**Comment by pcast01** [comment]
No problem. I did a lot more cleanup as well. We still need to update a lot of dependencies tho.
