### ISSUE TITLE
New Industry Partner

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#342]
Gent’s,
 
When possible, please add this link to our industry partners at the bottom of the homepage. https://skillnet.net
 If possible, please place it towars the top of the list of partner organizations.
 Than you so much – appreciate all of your hard work.
 Respectfully,
 
Dr. Richard L. “Monty” Gonzales
President, College of Biomedical Equipment Technology
11550 IH 10 West, Suite 190 | San Antonio | Texas  78230
O 210.233.1102  |  TF 844.879.9043  |  M 580.583.6817 | F 210.855.2245

**Comment by fpigeonjr** [comment]
![logo](https://user-images.githubusercontent.com/4629398/129353026-4952c128-b29b-4f2b-b5de-8d77d84c2a97.png)

**Comment by pcast01** [comment]
Completed.
