### ISSUE TITLE
New Partners

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/cbet#391]
Gents,
When possible, please add the following corporate partners to our cluster at the bottom of the page:
XMS Biomedical: [www.xmsbiomed.com](http://www.xmsbiomed.com/)
Safe Surgeries: https://safesurgeries.org/

Thank you and hope you are doing well.

**Comment by pcast01** [comment]
![Safe Logo 400dpiLogoCropped](https://user-images.githubusercontent.com/1172644/184721281-d1e11240-f3f9-44a1-9ebe-7fd3be021783.png)
![xms Biomedical logo](https://user-images.githubusercontent.com/1172644/184721859-e5117965-f71f-4c17-855a-aac1c918c87e.jpg)

**Comment by pcast01** [comment]
Added 2 partners to code.
